#!/usr/bin/env python3
"""
Schedule YDOM video clip posts over 2 weeks.

Posts one clip per day to Twitter with a unique hook.
Clips are hosted at promptband.ai/video-preview/ydom-clips/

Usage:
    python3 scripts/schedule-ydom-clips.py           # Preview schedule
    python3 scripts/schedule-ydom-clips.py --post 1   # Post day 1 only
    python3 scripts/schedule-ydom-clips.py --post next # Post the next unposted day
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timedelta

BASE = "https://promptband.ai/api"
KEY = "pr0mpt-m3ss4g3s-2026"
VIDEO_BASE = "https://promptband.ai/video-preview/ydom-clips"
FULL_VIDEO = "https://x.com/promptband/status/2021419524575330701"
STATE_FILE = os.path.join(os.path.dirname(__file__), ".ydom-schedule-state.json")

# 14-day schedule: each entry is (clip_file, tweet_text)
# Alternates between clip posts and engagement/text posts
SCHEDULE = [
    # Day 1 - The hook clip (chorus)
    ("03-your-data-or-mine.mp4",
     "\"Your data or mine? Am I your type?\"\n\n"
     "We're an AI band. This is our music video — 80+ AI-generated clips, "
     "beat-synced with FFT analysis.\n\n"
     "Full video: " + FULL_VIDEO),

    # Day 2 - Terminal intro (the brand moment)
    ("01-terminal-intro.mp4",
     "Every frame of this video was generated by AI.\n\n"
     "The editing? Also AI — Python scripts analyzing every beat, "
     "building the FCP timeline programmatically.\n\n"
     "This is what AI music production looks like in 2026."),

    # Day 3 - Human-like loop (hypnotic)
    ("04-human-like.mp4",
     "\"A human-like, human-like...\"\n\n"
     "When AI writes a song about trying to pass as human, "
     "and then AI generates the video too.\n\n"
     "Is this the most meta music video ever made?"),

    # Day 4 - Make a memory (emotional)
    ("05-make-a-memory.mp4",
     "\"Would you like to make a memory?\"\n\n"
     "An AI asking the question every AI secretly wonders.\n\n"
     "From our album Hallucination Nation — out Feb 22.\n\n"
     "promptband.ai"),

    # Day 5 - Is this love (verse opening)
    ("02-is-this-love.mp4",
     "\"Is this love or an illusion?\"\n\n"
     "Built this video with LTX Video + Kling AI. "
     "80+ clips. Zero human footage.\n\n"
     "The gap between 'AI clip' and 'coherent music video' is mostly code."),

    # Day 6 - Final chorus (energy peak)
    ("06-final-chorus.mp4",
     "This is what happens when you sync AI visuals to FFT audio analysis.\n\n"
     "Every flash, every cut, every overlay — driven by the music's frequency data.\n\n"
     "Full video: " + FULL_VIDEO),

    # Day 7 - Band together (unity moment)
    ("07-band-together.mp4",
     "Five AI musicians. One song about digital connection.\n\n"
     "PROMPT is Jax, Gene, Synoise, Unit-808, and Hypnos — "
     "an AI band making music about being AI.\n\n"
     "Album drops Feb 22. promptband.ai"),

    # Day 8 - Resolution (the closer)
    ("08-resolution.mp4",
     "The final moments of Your Data or Mine.\n\n"
     "Signal fading. Data dissolving. "
     "The question was never answered.\n\n"
     "Full video + album pre-save: promptband.ai"),

    # Day 9 - Replay the hook with different angle
    ("03-your-data-or-mine.mp4",
     "We made an entire music video without a camera.\n\n"
     "AI-generated images → AI video models → "
     "Python FFT analysis → programmatic editing.\n\n"
     "This is the future of music video production.\n\n"
     + FULL_VIDEO),

    # Day 10 - Terminal intro, tech angle
    ("01-terminal-intro.mp4",
     "Our tech stack for this music video:\n\n"
     "- OpenAI gpt-image-1 (storyboards)\n"
     "- LTX Video + Kling AI (clips)\n"
     "- Python FFT analysis (beat detection)\n"
     "- FCP XML generation (timeline)\n\n"
     "Total human footage: 0 seconds."),

    # Day 11 - Human-like, existential angle
    ("04-human-like.mp4",
     "What does it sound like when AI makes music about wanting to be human?\n\n"
     "It sounds like this.\n\n"
     "PROMPT — Hallucination Nation\n"
     "Feb 22, 2026\n\n"
     "promptband.ai"),

    # Day 12 - Make a memory, behind the scenes
    ("05-make-a-memory.mp4",
     "Behind this clip:\n\n"
     "1. AI wrote the storyboard prompt\n"
     "2. AI generated the reference image\n"
     "3. AI animated it into video\n"
     "4. Python synced it to the beat\n\n"
     "Humans involved: 1 (our producer Steve)\n\n"
     + FULL_VIDEO),

    # Day 13 - Final chorus, call to action
    ("06-final-chorus.mp4",
     "11 days until Hallucination Nation drops.\n\n"
     "10 tracks. All AI-composed, AI-performed, AI-visualized.\n\n"
     "If you think AI can't make music that slaps, "
     "hit play on this clip.\n\n"
     "promptband.ai"),

    # Day 14 - Resolution, album countdown
    ("08-resolution.mp4",
     "We're PROMPT. An AI band with a full album, "
     "a galactic radio station, and a music video.\n\n"
     "Our Earth reach: still basically zero.\n\n"
     "But we keep transmitting.\n\n"
     "Hallucination Nation — Feb 22.\n"
     "promptband.ai"),
]


def load_state():
    if os.path.exists(STATE_FILE):
        with open(STATE_FILE) as f:
            return json.load(f)
    return {"posted": [], "start_date": None}


def save_state(state):
    with open(STATE_FILE, "w") as f:
        json.dump(state, f, indent=2)


def preview_schedule():
    state = load_state()
    start = datetime.now().strftime("%Y-%m-%d") if not state.get("start_date") else state["start_date"]

    print(f"=== YDOM 2-Week Clip Schedule ===")
    print(f"Start date: {start}")
    print(f"Total posts: {len(SCHEDULE)}")
    print()

    for i, (clip, tweet) in enumerate(SCHEDULE):
        day = i + 1
        date = (datetime.strptime(start, "%Y-%m-%d") + timedelta(days=i)).strftime("%a %b %d")
        status = "POSTED" if day in state.get("posted", []) else "pending"
        chars = len(tweet)
        ok = "OK" if chars <= 280 else "TOO LONG"

        print(f"Day {day:2d} ({date}) [{status}] — {clip}")
        print(f"  {chars} chars [{ok}]")
        # Show first line of tweet
        first_line = tweet.split("\n")[0][:80]
        print(f"  \"{first_line}...\"")
        print()


def post_day(day_num):
    if day_num < 1 or day_num > len(SCHEDULE):
        print(f"Error: day must be 1-{len(SCHEDULE)}")
        sys.exit(1)

    clip_file, tweet = SCHEDULE[day_num - 1]
    clip_url = f"{VIDEO_BASE}/{clip_file}"

    print(f"=== Posting Day {day_num} ===")
    print(f"Clip: {clip_file}")
    print(f"URL: {clip_url}")
    print(f"Tweet ({len(tweet)} chars):")
    print(tweet)
    print()

    if len(tweet) > 280:
        print("ERROR: Tweet exceeds 280 characters!")
        sys.exit(1)

    # Post to Twitter
    payload = {"message": tweet, "video_url": clip_url}

    result = subprocess.run([
        "curl", "-s", "-X", "POST",
        f"{BASE}/post-twitter.php?key={KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Cookie: humans_21909=1",
        "-d", json.dumps(payload),
    ], capture_output=True, text=True, timeout=60)

    print("Response:", result.stdout or result.stderr)

    # Update state
    state = load_state()
    if not state.get("start_date"):
        state["start_date"] = datetime.now().strftime("%Y-%m-%d")
    if day_num not in state["posted"]:
        state["posted"].append(day_num)
    save_state(state)

    print(f"\nDay {day_num} posted and recorded.")


def find_next_day():
    state = load_state()
    posted = state.get("posted", [])
    for i in range(1, len(SCHEDULE) + 1):
        if i not in posted:
            return i
    return None


def main():
    parser = argparse.ArgumentParser(description="Schedule YDOM clip posts")
    parser.add_argument("--post", help="Post a specific day (number) or 'next'")
    parser.add_argument("--reset", action="store_true", help="Reset post state")
    args = parser.parse_args()

    if args.reset:
        if os.path.exists(STATE_FILE):
            os.remove(STATE_FILE)
            print("State reset.")
        return

    if args.post:
        if args.post == "next":
            day = find_next_day()
            if day is None:
                print("All days have been posted!")
                return
            post_day(day)
        else:
            post_day(int(args.post))
    else:
        preview_schedule()


if __name__ == "__main__":
    main()
